### ISSUE TITLE
"dial tcp 127.0.0.1:80: connect: connection refused" on kubernetes-addons module

### ISSUE THREAD

**Issue by hksfho** [aws-samples/aws-eks-accelerator-for-terraform#156]
I am running terraform using gitlab-ci and there are some unsupported variable errors thrown today. 
After chasing for a while, I observed that the main branch has been updated. The k8s addon config has been refactored as a sub-module. So I updated my terraform code from

```
module "eks" {
  source = "github.com/aws-samples/aws-eks-accelerator-for-terraform"

  tenant      = local.tenant
  environment = local.environment
  zone        = local.zone

  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets

  create_eks         = true
  kubernetes_version = local.kubernetes_version

  managed_node_groups = {
    ondemand = {
      # Node Group configuration
      node_group_name = "managed-ondemand"

      # Node Group scaling configuration
      desired_size = local.desired_size
      min_size     = local.min_size
      max_size     = local.max_size

      # Node Group compute configuration
      capacity_type  = "ON_DEMAND"
      instance_types = [local.instance_type]
      disk_size      = 50

      # Node Group network configuration
      subnet_ids = module.vpc.private_subnets
    }
  }

  #K8s Add-ons
  aws_lb_ingress_controller_enable = true
  metrics_server_enable            = true
  cluster_autoscaler_enable        = true
}
```

to 

```
module "kubernetes-addons" {
  source = "github.com/aws-samples/aws-eks-accelerator-for-terraform//modules/kubernetes-addons"

  eks_cluster_id = module.eks.eks_cluster_id

  # EKS Addons
  enable_amazon_eks_vpc_cni    = true
  enable_amazon_eks_coredns    = true
  enable_amazon_eks_kube_proxy = true

  #K8s Add-ons
  enable_aws_load_balancer_controller = true
  enable_metrics_server               = true
  enable_cluster_autoscaler           = true

}
```

Unfortunately, the terraform apply is failed.
```
module.makeitfun_eks.module.kubernetes-addons.module.aws_coredns[0].aws_eks_addon.coredns: Still creating... [6m40s elapsed]
module.makeitfun_eks.module.kubernetes-addons.module.aws_coredns[0].aws_eks_addon.coredns: Still creating... [6m50s elapsed]
module.makeitfun_eks.module.kubernetes-addons.module.aws_coredns[0].aws_eks_addon.coredns: Still creating... [7m0s elapsed]
module.makeitfun_eks.module.kubernetes-addons.module.aws_coredns[0].aws_eks_addon.coredns: Creation complete after 7m4s [id=makeitfun-development-all-eks:coredns]
╷
│ Error: Post "http://localhost/api/v1/namespaces/kube-system/serviceaccounts": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.makeitfun_eks.module.kubernetes-addons.module.aws_load_balancer_controller[0].kubernetes_service_account.aws_load_balancer_controller_sa,
│   on .terraform/modules/makeitfun_eks.kubernetes-addons/modules/kubernetes-addons/aws-load-balancer-controller/main.tf line 346, in resource "kubernetes_service_account" "aws_load_balancer_controller_sa":
│  346: resource "kubernetes_service_account" "aws_load_balancer_controller_sa" {
│ 
╵
╷
│ Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
│ 
│   with module.makeitfun_eks.module.kubernetes-addons.module.cluster_autoscaler[0].helm_release.cluster_autoscaler[0],
│   on .terraform/modules/makeitfun_eks.kubernetes-addons/modules/kubernetes-addons/cluster-autoscaler/main.tf line 19, in resource "helm_release" "cluster_autoscaler":
│   19: resource "helm_release" "cluster_autoscaler" {
│ 
╵
╷
│ Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
│ 
│   with module.makeitfun_eks.module.kubernetes-addons.module.metrics_server[0].helm_release.metrics_server[0],
│   on .terraform/modules/makeitfun_eks.kubernetes-addons/modules/kubernetes-addons/metrics-server/main.tf line 19, in resource "helm_release" "metrics_server":
│   19: resource "helm_release" "metrics_server" {
│ 
╵
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 1
```
https://i.ibb.co/8zfv4st/Screenshot-2021-12-28-at-5-56-55-PM.png

Does it seem the submodule cannot ready the newly created kube config? 

here is my gitlab-ci:
```
default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - echo "Initialing..."
    - terraform init -backend-config=vars/backend.hcl.json -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
    - terraform workspace select ${CI_COMMIT_REF_NAME}
  cache:
    key: terraform
    paths:
      - .terraform

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  environment:
    name: ${CI_COMMIT_REF_NAME}
  only:
    - development
  script:
    - terraform validate

plan:
  stage: plan
  environment:
    name: ${CI_COMMIT_REF_NAME}
  only:
    - development
  script:
    - terraform plan -var-file=vars/$CI_COMMIT_REF_NAME/variables.tfvars
  dependencies:
    - validate

apply non production:
  stage: apply
  environment:
    name: ${CI_COMMIT_REF_NAME}
  only:
    - development
  script:
    - terraform apply -var-file=vars/$CI_COMMIT_REF_NAME/variables.tfvars -input=false -refresh=true -auto-approve=true
  dependencies:
    - plan

apply production:
  extends: apply non production
  when: manual
  only:
    - master

```
